### PR TITLE
Add links to Contributors Twitter accounts.

### PR DESCRIPTION
**Pull request by joshuapinter**

### CODE REVIEW

**Comment by lwe** [comment]
Are you positive these are the correct Twitter profiles for each involved, maybe we should only link those who are 100% correct.

**Comment by joshuapinter** [comment]
Oh, good call. I thought that's what you were implying with the `@` symbol but I guess it's probably best to link to their Github accounts instead. Are those their Github usernames?

**Comment by lwe** [comment]
Jep, these are actually GH usernames, but if available we could link both, i.e. the `@xyz` to link to GitHub and if available a link like e.g. `[Twitter](https://twitter.com/lukw)`, what do you think?

**Comment by joshuapinter** [comment]
I think linking to their Github account would be just fine. They'll have their twitter account on their profile page. Good catch! 

Lemme update the PR.

**Comment by joshuapinter** [comment]
Okay, updated. Only `sinsiliux` was not a valid profile so I just removed the link for him/her.

**Comment by lwe** [comment]
cool thanks.

**Comment by joshuapinter** [comment]
:+1:

**Pull request merged**
