### PR TITLE
Rewrite mongoid, use 'accessor.source'

### PR DESCRIPTION
**Pull request by bbtfr**
I've found an issue during writing the code:
`genders_accessor` method only exists when `with.include? :class`, otherwise, it will raise a `NoMethodError`, it's kinda tricky.

So I add an `accessor` attribute to `enum`, but in fact, I don't like it either, because it's weird that we have `enum.accessor` and `accessor.enum`, and if we use `attr_accessor :accessor`, people can change `enum.accessor` by themselves, if not, aka: `attr_reader :accessor`, we have to use something like `instance_variable_set`.

### CODE REVIEW

**Comment by bbtfr** [comment]
What do you think if `as_enum` returns an `accessor`, obviously, it will cause an incompatibility issue, but I don't think people will use the return value of `as_enum`

**Comment by lwe** [comment]
Thanks, for 2.x I want to keep it returning the `enum`, but I'm aware that this was maybe a poor choice.

**Comment by bbtfr** [comment]
OK, understood, thanks for your time and generous help.

**Comment by lwe** [comment]
Thank *you* and let me know when your plugins are completed.

**Pull request merged**
